---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Centos)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Centos"

  - name: install updates (Ubuntu)
    apt:
       upgrade: dist
       update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_server
  become: true
  tasks:

  - name: install apache2 and php support package
    apt:
       name: 
         - apache2
         - libapache2-mod-php
       state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install apache2 and php support package
    dnf:
       name:
         - httpd
         - php
       state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_server
  become: true
  tasks:

   - name: install mariadb package(Ubuntu)
     apt:
        name: mariadb-server
        state: latest
     when: ansible_distribution == "Ubuntu"
